### ISSUE TITLE
Eliminate more outer joins by supporting more expressions, like UDFs

### ISSUE THREAD

**Issue by Dandandan** [apache/datafusion#13232]
### Is your feature request related to a problem or challenge?

This PR by @JasonLi-cn tried to support more pushdown https://github.com/apache/datafusion/pull/13184 , however the implementation wasn't 100% right as it pushed down more predicates, but didn't change the join type.

### Describe the solution you'd like

Add support for a wider range of expressions in `EliminateOuterJoin`, notably in `extract_non_nullable_columns`.
We lack support of more complex nested expressions, quite some binary operators, UDFs etc.

**Comment by Rachelint** [comment]
take

**Comment by JasonLi-cn** [comment]
> Rachelint

I have implemented a preliminary version and am happy to solve this Issue together. 😄

pr: https://github.com/apache/datafusion/pull/13249

**Comment by suibianwanwank** [comment]
Hi everyone, I have submitted a new PR based on https://github.com/apache/datafusion/pull/13249 (adding additional methods to handle more cases). Looking forward to your feedback! 😊

**Comment by neilconway** [comment]
#22444 should have improved this situation somewhat. We still don't consider UDFs to ever be null-rejecting, which is a fairly big hole.

**Comment by neilconway** [comment]
#22534 is another incremental improvement here.
