### ISSUE TITLE
Release DataFusion `51.0.0` (Nov 2025)

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#17558]
### Is your feature request related to a problem or challenge?

Tracking ticket for next release, also a place to track desired inclusions

Previous release will be https://github.com/apache/datafusion/issues/16799 (Sep, 2025) so next major release would be approximately late Nov 2025

Steps:
- [x] Create a `branch-51` branch: https://github.com/apache/datafusion/tree/branch-51
- [x]  Update version and changelog: https://github.com/apache/datafusion/pull/18551
- [ ] Test with DataFusion Python
- [x] Test with DataFusion Comet 
- [x] Test with delta.rs:
- [x] Test vortex: 
- [x] Test with iceberg-rust: 
- [x] Test with LakeSail:
- [ ] Test with parquet viewer
- [x] Test with datafusion-materialized-views
- [ ] Voting Thread: 
- [ ] Publish to crates.io
- [x]  Create ticket for next release: https://github.com/apache/datafusion/issues/18566
- [ ] Create blog post: https://github.com/apache/datafusion/issues/18548

TODOs
-

Prior release tickets:
* https://github.com/apache/datafusion/issues/16799

Related
- Boston USA Nov 2025 meetup: https://github.com/apache/datafusion/discussions/16703

# Features to mention in the blog (if they make it)
- [x] https://github.com/apache/datafusion/pull/17501 from @AdamGS 
- [x] https://github.com/apache/datafusion/pull/17278#event-19853149118
- [x] https://github.com/apache/datafusion/issues/18118
- [x] https://github.com/apache/datafusion/issues/17207
- [ ] https://github.com/apache/datafusion/issues/18075
- [ ] https://github.com/apache/datafusion/pull/16771
- [ ] https://github.com/apache/datafusion/issues/17824 from the @theirix 

## Issuses needed
- [x] https://github.com/apache/datafusion/issues/18204

## Bugs that should be fixed
- [x] https://github.com/apache/datafusion/issues/17624
- [x] https://github.com/apache/datafusion/issues/17401
- [x] https://github.com/apache/datafusion/issues/18334
- [x] https://github.com/apache/datafusion/issues/17770 / https://github.com/apache/datafusion/pull/17852
- [x] https://github.com/apache/datafusion/issues/18062
- [x] https://github.com/apache/datafusion/issues/18219
- [x] https://github.com/apache/datafusion/issues/16678
- [ ] https://github.com/apache/datafusion/issues/17801
- [ ] https://github.com/apache/datafusion/issues/18527

# Community Wishlist
- [ ] https://github.com/apache/datafusion/issues/16919
- [ ] https://github.com/apache/datafusion/issues/13323
- [ ] https://github.com/apache/arrow-rs/pull/8496
- [ ] https://github.com/apache/datafusion/pull/18025

**Comment by mjgarton** [comment]
Should the title of this issue say 51.0.0 instead of 50.0.0?

**Comment by xudong963** [comment]
> Should the title of this issue say 51.0.0 instead of 50.0.0?

yes, thank you, i changed it.

**Comment by findepi** [comment]
I removed https://github.com/apache/datafusion/pull/16842 from "Changes to add to upgrade guide". I think it was completed in 50.0.0. If not, let's add it back.

**Comment by xudong963** [comment]
I think we could start working on the release next week?

**Comment by rluvaton** [comment]
If we could get the following arrow fix merged and released as a patch and upgrade to that patch before the upcoming release it would be sweet:
- https://github.com/apache/arrow-rs/pull/8496

**Comment by alamb** [comment]
> If we could get the following arrow fix merged and released as a patch and upgrade to that patch before the upcoming release it would be sweet:
> 
> * [fix(parquet): converting parquet schema with backward compatible repeated struct/primitive with provided arrow schema arrow-rs#8496](https://github.com/apache/arrow-rs/pull/8496)

I think that one will be released in arrow 57.1.0 (a minor update that won't require a datafusion upgrade). 

So once we have released datafusion 51 we'll be able to do a minor update to arrow 57.1.0

(in other words, I don't think the release timeline of DataFusion will impact the flow of that PR)

**Comment by xudong963** [comment]
FYI, I plan to cut the 51.0.0 in the next two days. Do we have some high-priority PRs waiting for review?

**Comment by pepijnve** [comment]
> FYI, I plan to cut the 51.0.0 in the next two days. Do we have some high-priority PRs waiting for review?

#18444 and #18183 are the remaining two for the `CASE` epic. Would be nice if we could still get those in.

**Comment by alamb** [comment]
@Omega359  do we have additional work needed for the default timezone fixes?
- E.g. follow ups from https://github.com/apache/datafusion/pull/18359

**Comment by Omega359** [comment]
@alamb - the outstanding ones I've got on my radar are 
- https://github.com/apache/datafusion/pull/18025
- https://github.com/apache/datafusion/pull/18408 (new feature, not in critical path)
- https://github.com/apache/datafusion/pull/18417 (been broken for quite a while now)

I'd like to get the first one in for 51.0.0. The other two while nice to have I do not see as critical

**Comment by alamb** [comment]
> I'd like to get the first one in for 51.0.0. The other two while nice to have I do not see as critical

Thanks @Omega359  -- added it to the list above

I also think we need to fix this regression:
- https://github.com/apache/datafusion/issues/17801

**Comment by shehabgamin** [comment]
We're working on testing Sail on our end.

**Comment by AdamGS** [comment]
Testing with Vortex [here](https://github.com/vortex-data/vortex/pull/5189)

**Comment by xudong963** [comment]
I'm testing with mv repo tomorrow. 

It would be nice to cut and vote at Friday (I'm off on the weekend)

**Comment by milenkovicm** [comment]
ballista tested with commit 32d26187a358aaa0803867a7963cd149ec1fcd1e and looks ok 👍🏻

**Comment by xudong963** [comment]
mv repo looks good: https://github.com/datafusion-contrib/datafusion-materialized-views/pull/104

**Comment by pepijnve** [comment]
> I also think we need to fix this regression:
> https://github.com/apache/datafusion/issues/17801

Regarding that regression, I'm happy to help out with getting this fixed but I got a bit stuck in figuring out what the most appropriate solution is. I've written down what I've tried so far in [the comment thread of that issue](https://github.com/apache/datafusion/issues/17801#issuecomment-3497492805). If I could get some help in deciding how to proceed we should be able to resolve this fairly quickly.

**Comment by alamb** [comment]
I made a PR to upgrade delta.rs and I didn't find anything show stopping
- https://github.com/delta-io/delta-rs/pull/3921

**Comment by mbutrovich** [comment]
> I made a PR to upgrade delta.rs and I didn't find anything show stopping
> 
> * [feat: update to DataFusion 51.0.0 delta-io/delta-rs#3921](https://github.com/delta-io/delta-rs/pull/3921)

How did you pick that commit? There's no branch-51 yet, so unsure what will make the cut. Should I test Comet with latest main commit?

**Comment by alamb** [comment]
> How did you pick that commit? There's no branch-51 yet, so unsure what will make the cut. Should I test Comet with latest main commit?


Yes I just picked the latest main commit 🤷

**Comment by shehabgamin** [comment]
> I made a PR to upgrade delta.rs and I didn't find anything show stopping
> 
>     * [feat: update to DataFusion 51.0.0 delta-io/delta-rs#3921](https://github.com/delta-io/delta-rs/pull/3921)

@alamb We should coordinate on the next release. It looks like we can save some duplicated effort:
https://github.com/lakehq/delta-rs/pull/2

## Testing With Sail
@lonless9 made a PR to upgrade to DataFusion 51:
https://github.com/lakehq/sail/pull/1031

### Breaking Changes
- PyO3
- Tonic

### Regressions
One of our tests related to window functions is failing with the error:
```
Expects PARTITION BY expression to be ordered
```

Here is the test in question:
https://github.com/lakehq/sail/blob/8bc2a05d595f02aba3a23fcd26aef81df36a7b96/python/pysail/tests/spark/test_execution.py#L124-L148

We likely won’t have the bandwidth to dig deeper in time for the release, but it’s something worth looking into, IMO.

**Comment by milenkovicm** [comment]
> > How did you pick that commit? There's no branch-51 yet, so unsure what will make the cut. Should I test Comet with latest main commit?
> 
> Yes I just picked the latest main commit 🤷

Random sample, cornerstone of good quality control 😀 (just kidding)

**Comment by alamb** [comment]
@shehabgamin  -- thank you

> > I made a PR to upgrade delta.rs and I didn't find anything show stopping
> > ```
> > * [feat: update to DataFusion 51.0.0 delta-io/delta-rs#3921](https://github.com/delta-io/delta-rs/pull/3921)
> > ```
> 
> [@alamb](https://github.com/alamb) We should coordinate on the next release. It looks like we can save some duplicated effort: [lakehq/delta-rs#2](https://github.com/lakehq/delta-rs/pull/2)

Thanks! Yes that would  be great -- it would be super helpful. I started my testing about the same time as @lonless9  filed https://github.com/delta-io/delta-rs/pull/3921 -- hopefully next time we'll avoid the duplication

> ## Testing With Sail
> [@lonless9](https://github.com/lonless9) made a PR to upgrade to DataFusion 51: [lakehq/sail#1031](https://github.com/lakehq/sail/pull/1031)

❤️ 

> ```
> Expects PARTITION BY expression to be ordered
> ```
> 
> Here is the test in question: https://github.com/lakehq/sail/blob/8bc2a05d595f02aba3a23fcd26aef81df36a7b96/python/pysail/tests/spark/test_execution.py#L124-L148

Thanks -- I looked at that briefly at that test and it isn't clear where "Expects PARTITION BY expression to be ordered" is coming from. While the window function does have a `partition by` expression, I don't see why the partition by would be ordered. 

I filed a ticket to track it
- https://github.com/apache/datafusion/issues/18527

**Comment by mbutrovich** [comment]
Starting to test with Comet: https://github.com/apache/datafusion-comet/pull/2729

**Comment by alamb** [comment]
Given the current state of tests, I think we should cut `branch-51` tomorrow (and backport anything else we need to get the release out).

I think @xudong963  said he was away this weekend, so I'll plan to make the branch tomorrow morning unless I hear otherwise

**Comment by mbutrovich** [comment]
I started [testing with iceberg-rust](https://github.com/apache/iceberg-rust/pull/1830) and the blast radius is pretty big for that project, so Comet might lag behind DF 51 a bit to help get iceberg-rust sorted. That's not a -1 or anything from me though. DF 51 looks good from Comet's end.

**Comment by alamb** [comment]
I have created the branch here:
- https://github.com/apache/datafusion/tree/branch-51

I think this issue needs to be fixed prior to release (I will make a PR to revert the offending commits shortly)
- [ ] https://github.com/apache/datafusion/issues/17801

This one (raised by @shehabgamin) would be nice to look at as well
- [ ] https://github.com/apache/datafusion/issues/18527

**Comment by alamb** [comment]
I also filed a ticket for a blog post 🎣 
- https://github.com/apache/datafusion/issues/18548

**Comment by alamb** [comment]
I have made a PR to revert the coalesce/nvl/nvl2 rewrites
- https://github.com/apache/datafusion/pull/18567

**Comment by xudong963** [comment]
Thank you @alamb, I followed the current status, looks like the only blocker is https://github.com/apache/datafusion/issues/18527?

**Comment by alamb** [comment]
> Thank you [@alamb](https://github.com/alamb), I followed the current status, looks like the only blocker is [#18527](https://github.com/apache/datafusion/issues/18527)?

Maybe -- I don't think that ticket is actionable at the moment (it doesn't have enough information to reproduce / understand what is potentially wrong)

Unless @shehabgamin  or someone from his team can help triage / provide more information I think we should not treat https://github.com/apache/datafusion/issues/18527 as a blocker.

**Comment by xudong963** [comment]
> Unless [@shehabgamin](https://github.com/shehabgamin) or someone from his team can help triage / provide more information I think we should not treat [#18527](https://github.com/apache/datafusion/issues/18527) as a blocker.

Let's wait for one day, I may start the vote process tomorrow (UTC+8)

**Comment by xudong963** [comment]
FYI, Just started the vote process

**Comment by timsaucer** [comment]
Found another regression I think: https://github.com/apache/datafusion/issues/18622

**Comment by comphead** [comment]
@hareshkh wanna include https://github.com/apache/datafusion/pull/18596 to the release

**Comment by comphead** [comment]
> FYI, Just started the vote process

@xudong963 please share  the vote link?

**Comment by xudong963** [comment]
> > FYI, Just started the vote process
> 
> [@xudong963](https://github.com/xudong963) please share the vote link?

Here, https://lists.apache.org/thread/32dcnyrhcjxg6scx2wjv9m6m22skft32.

But I think the RC1 failed, let's wait for RC2

**Comment by xudong963** [comment]
It seems like all PRs are added to branch-51, cc @comphead @timsaucer 

Time to start the RC2

**Comment by xudong963** [comment]
> Time to start the RC2

I think we still need to update changelog before releasing, will do later

**Comment by xudong963** [comment]
> > Time to start the RC2
> 
> I think we still need to update changelog before releasing, will do later

Could anyone help do this? My network has been bad for a long time:
```
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Request GET /repos/apache/datafusion/commits/e14322da196a75bea2de2be560b93ea7c8e83d11/pulls failed with 403: rate limit exceeded
Setting next backoff to 3503.394145s
```

**Comment by alamb** [comment]
> 
> Could anyone help do this? My network has been bad for a long time:
> 
> ```
> . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Request GET /repos/apache/datafusion/commits/e14322da196a75bea2de2be560b93ea7c8e83d11/pulls failed with 403: rate limit exceeded
> Setting next backoff to 3503.394145s
> ```

Done!
- https://github.com/apache/datafusion/pull/18705

BTW this happens to me when I don't use my github token (the rate limit is apparently much stricter). I made a PR to add a note to the docs:
- https://github.com/apache/datafusion/pull/18704

**Comment by xudong963** [comment]
@alamb thank you, just started the vote process https://lists.apache.org/thread/k2ygp0c1rp56ww44lljf0yg6qf60q5f7

**Comment by xudong963** [comment]
Done

**Comment by alamb** [comment]
Thank you @xudong963  -- amazing as alwasy
