### ISSUE TITLE
Support complete `distinct` usage for aggregate expressions

### ISSUE THREAD

**Issue by WinkerDu** [apache/datafusion#2406]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Here are multiple aggregate expressions have not support `distinct` usage yet.
Though optimizer `SingleDistinctToGroupBy` (#1315) supports single distinct usage, there are more SQL scenes have not been covered, like
```
SELECT AVG(c1), SUM(DISTINCT c2) FROM test
```
I would like to take effort to work on the following tickets to complete `distinct` usage for aggregate expressions

- [x] #2405
- [x] #2407 
- [x] #2408
- [x] #2409
- [ ] #2410
- [x] #2411
(more to be added later)

**Describe the solution you'd like**
Adds specific aggregate expression support, like `expressions::DistinctSum` for `sum(distinct)`

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by WinkerDu** [comment]
@andygrove @alamb can you please assign this issue to me?

**Comment by alamb** [comment]
> @andygrove @alamb can you please assign this issue to me? Thank you ❤️

Done -- thanks @WinkerDu

**Comment by Dandandan** [comment]
All done

**Comment by Jefffrey** [comment]
I think there's still some that weren't listed here that still don't support distinct.

## Explicitly denies

stddev

https://github.com/apache/datafusion/blob/bb121a8fcdb9ca7fa53ee8bcf175844e2a6df7f3/datafusion/functions-aggregate/src/stddev.rs#L118-L123

approx_median

https://github.com/apache/datafusion/blob/bb121a8fcdb9ca7fa53ee8bcf175844e2a6df7f3/datafusion/functions-aggregate/src/approx_median.rs#L130-L135

## May be missing support

These functions don't explicitly use the `distinct` flag to handle distinct specific behaviour, but depending on their semantics maybe distinct doesn't make sense for them? Anyway just listing them:

- https://github.com/apache/datafusion/blob/bb121a8fcdb9ca7fa53ee8bcf175844e2a6df7f3/datafusion/functions-aggregate/src/regr.rs
- https://github.com/apache/datafusion/blob/bb121a8fcdb9ca7fa53ee8bcf175844e2a6df7f3/datafusion/functions-aggregate/src/nth_value.rs
- https://github.com/apache/datafusion/blob/bb121a8fcdb9ca7fa53ee8bcf175844e2a6df7f3/datafusion/functions-aggregate/src/covariance.rs
- https://github.com/apache/datafusion/blob/bb121a8fcdb9ca7fa53ee8bcf175844e2a6df7f3/datafusion/functions-aggregate/src/correlation.rs
- https://github.com/apache/datafusion/blob/bb121a8fcdb9ca7fa53ee8bcf175844e2a6df7f3/datafusion/functions-aggregate/src/approx_percentile_cont.rs
